[package]
name = "pix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15"
indexmap = "2"
indicatif = "0.17"
once_cell = "1"
regex = "1"
serde_json = "1"
serde_repr = "0.1"
serde = { version = "1", features = ["derive"] }
